name: Build Docker Container

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v2
        with:
          docker-version: '20.10.7' # You can specify the Docker version you need

      - name: Build Docker Image
        run: docker build -t apt-mirror:latest . # Replace 'your-image-name' with your desired image name
        working-directory: . # Specify the directory where your Dockerfile is located

      # Optional: Push the Docker image to a container registry (e.g., Docker Hub, GitHub Container Registry)
      # Uncomment and configure these steps if you want to push the image.
      # - name: Log in to Docker Hub
      #   run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # - name: Push Docker Image
      #   run: docker push your-image-name:latest

      # - name: Log out of Docker Hub
      #   run: docker logout

# You can add more steps or customize this workflow to suit your needs.
